dont require https for localhost
microsoft/kiota-authentication-azure-go pull request #102
Opened 2023-10-12 07:54 UTC by NerdJeremia

2023-10-12 07:55 UTC, NerdJeremia commented
@microsoft-github-policy-service agree

2023-10-12 12:38 UTC, baywet requested changes
Thanks for the contribution.
In addition to the comments I left can you:
- add unit tests
- add an entry in the changelog (bump the patch version, set the date to tomorrow)

Thanks!

2023-10-12 12:38 UTC, baywet commented on azure_identity_access_token_provider.go
> +	if strings.HasPrefix(host, "localhost") {
we should normalize the host to lowercase before making the comparison

2023-10-12 12:38 UTC, baywet commented on azure_identity_access_token_provider.go
> +		remainder := strings.TrimPrefix(host, "localhost")
use constants for values like localhost

2023-10-12 12:38 UTC, baywet commented on azure_identity_access_token_provider.go
> +		return remainder == "" || strings.HasPrefix(remainder, ":")
move the remainder check to a dedicated method to avoid duplication

2023-10-12 12:38 UTC, baywet commented on azure_identity_access_token_provider.go
> +	}
we're missing a case for "[::1]" (Ipv6) ("::1" is also valid)

2023-10-12 16:19 UTC, baywet requested changes

2023-10-12 16:19 UTC, baywet commented on azure_identity_access_token_provider.go
> +	if strings.HasPrefix(normalizedHost, Localhost) {
::1 is also valid. You could make the const an array and iterate over the array instead.

2023-10-13 14:47 UTC, baywet approved these changes
Thanks for the contribution!

2023-10-13 14:52 UTC, baywet commented on azure_identity_access_token_provider.go
> +var LocalhostStrings = [3]string{"localhost", "[::1]", "::1", "127.0.0.1"}
```suggestion
var LocalhostStrings = [4]string{"localhost", "[::1]", "::1", "127.0.0.1"}
```

2023-10-13 14:52 UTC, baywet approved these changes

2023-10-13 14:54 UTC, merged